### ISSUE TITLE
Node broken when I updated NR to 1.2

### ISSUE THREAD

**Issue by cymplecy** [razorRun/node-red-contrib-smartlifeair#14]
I updated to NR 1.2.0 yesterday and the node isn't working and giving lots of errors in the log.

Downgrading back to NR 1.1.0 hasn't helped

I stupidly updated npm at the same time so it might be an npm issue and not to do with NR

Sample of errors in log

` at Client.parse (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\client.js:62:58)
    at IO.write (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:709:20)
    at TLSSocket.emit (events.js:198:13)
(node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 105)
[2020-10-16T08:15:34.387Z]  @firebase/database: FIREBASE WARNING: set at /devices/351278822cf4326e03b3/commands failed: permission_denied
(node:11020) UnhandledPromiseRejectionWarning: Error: PERMISSION_DENIED: Permission denied
    at C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:12880:33
    at exceptionGuard (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:698:9)
    at Repo.callOnCompleteCallback (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:12870:13)
    at C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:12683:19
    at C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:11900:17
    at PersistentConnection.onDataMessage_ (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:11930:17)
    at Connection.onDataMessage_ (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:11247:14)
    at Connection.onPrimaryMessageReceived_ (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:11241:18)
    at WebSocketConnection.onMessage (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:11142:27)
    at WebSocketConnection.appendFrame_ (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:10728:18)
    at WebSocketConnection.handleIncomingFrame (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:10779:22)
    at Client.mySock.onmessage (C:\Users\Simon\.node-red\node_modules\@firebase\database\dist\index.node.cjs.js:10674:19)
    at Client.dispatchEvent (C:\Users\Simon\.node-red\node_modules\@firebase\database\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:24:30)
    at Client._receiveMessage (C:\Users\Simon\.node-red\node_modules\@firebase\database\node_modules\faye-websocket\lib\faye\websocket\api.js:152:10)
    at Client.<anonymous> (C:\Users\Simon\.node-red\node_modules\@firebase\database\node_modules\faye-websocket\lib\faye\websocket\api.js:36:49)
    at Client.emit (events.js:203:15)
    at Client.<anonymous> (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\hybi.js:454:14)
    at pipe (C:\Users\Simon\.node-red\node_modules\websocket-extensions\lib\pipeline\index.js:37:40)
    at Pipeline._loop (C:\Users\Simon\.node-red\node_modules\websocket-extensions\lib\pipeline\index.js:44:3)
    at Pipeline.processIncomingMessage (C:\Users\Simon\.node-red\node_modules\websocket-extensions\lib\pipeline\index.js:13:8)
    at Extensions.processIncomingMessage (C:\Users\Simon\.node-red\node_modules\websocket-extensions\lib\websocket_extensions.js:133:20)
    at Client._emitMessage (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\hybi.js:445:22)
    at Client._emitFrame (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\hybi.js:405:19)
    at Client.parse (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\hybi.js:141:18)
    at Client.parse (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\driver\client.js:62:58)
    at IO.write (C:\Users\Simon\.node-red\node_modules\websocket-driver\lib\websocket\streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:709:20)
    at TLSSocket.emit (events.js:198:13)
(node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 106)`

**Comment by cymplecy** [comment]
NR 1.2.2 was issued today and after I upgraded to it - my errors have gone
